### PR TITLE
Create hello.cpp

### PR DESCRIPTION
**Pull request by virendrasingal**

### CODE REVIEW

**Comment by virendrasingal** [comment]
can  i  written  in another language

**Comment by mekowalski** [comment]
You can keep the language you wrote it in just write what language it's in above.  What I wrote in the first comment is an example. You can also view other `hello_world` files to see the different languages and have an idea of how to format your script.  Hope that makes sense.

-Malind

**Comment by virendrasingal** [comment]
Now you see the code and then suggest me!!

**Comment by virendrasingal** [comment]
yes!!

**Comment by mekowalski** [comment]
Yeah! Go ahead and add your profile whenever!

Happy coding, 
Malind

**Pull request merged**
